{% set version = "2023.0.0" %}

package:
  name: ldrb
  version: {{ version }}

source:
  url: https://github.com/finsberg/ldrb/archive/v{{ version }}.tar.gz
  sha256: 11e59b73a9cfe93eb10ede92e13658b3c80687c2425b555e8f87449c705d315d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fenics
    - quaternion
    - h5py
    - numba
    - numpy
test:
  imports:
    - ldrb
about:
  home: https://github.com/finsberg/ldrb
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Laplace-Dirichlet Rule-based algorithm for assigning myocardial fiber orientations

  description: |
    A software for assigning myocardial fiber orientations based on the 
    Laplace Dirichlet Ruled-Based algorithm from Bayer, J.D., Blake, R.C., Plank, G. and Trayanova, N.A., 2012.
    A novel rule-based algorithm for assigning myocardial fiber orientation
    to computational heart models. Annals of biomedical engineering, 40(10), pp.2243-2254
  doc_url: http://finsberg.github.io/ldrb
  dev_url: https://github.com/finsberg/ldrb
extra:
  recipe-maintainers:
    - finsberg
