{% set version = "2023.3.1" %}

package:
  name: ldrb
  version: {{ version }}

source:
  url: https://github.com/finsberg/ldrb/archive/v{{ version }}.tar.gz
  sha256: 43b73a8e5a98cb310e79a5402413f69c1f91fe6c7a73b80cf03ecabf76a0e376

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fenics
    - h5py
    - numba
    - numpy
    - scipy >0.16

test:
  imports:
    - ldrb
about:
  home: https://github.com/finsberg/ldrb
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Laplace-Dirichlet Rule-based algorithm for assigning myocardial fiber orientations

  description: |
    A software for assigning myocardial fiber orientations based on the 
    Laplace Dirichlet Ruled-Based algorithm from Bayer, J.D., Blake, R.C., Plank, G. and Trayanova, N.A., 2012.
    A novel rule-based algorithm for assigning myocardial fiber orientation
    to computational heart models. Annals of biomedical engineering, 40(10), pp.2243-2254
  doc_url: http://finsberg.github.io/ldrb
  dev_url: https://github.com/finsberg/ldrb
extra:
  recipe-maintainers:
    - finsberg
